Adding federated token logs & optional audience parameter
Azure/login pull request #159
Opened 2021-10-25 13:26 UTC by BALAGA-GAYATRI

Added federated token logs - sample output:
<img width="598" alt="Screenshot 2021-10-25 at 7 00 15 PM" src="https://user-images.githubusercontent.com/26038662/138704781-ffa3480b-841c-4fbc-bd30-5dfdd800c1fa.png">

Also, added audience parameter (which will be optional) and defaults to ‘api://AzureADTokenExchange’

2021-11-08 09:46 UTC, kaverma commented on README.md
> +Users can also specify `audience` field for access-token in the input parameters of the action. If not specified, it is defaulted to `api://AzureADTokenExchange`. This action supports login az powers
nit: we should have "This action supports login... " in a new line

2021-11-08 09:48 UTC, kaverma approved these changes

2021-11-08 11:08 UTC, kaverma commented
We need to update the documentation/readme to include the audience field

2021-11-09 10:42 UTC, kaverma requested changes
@BALAGA-GAYATRI, @N-Usha , should we have a security review to ensure whether we are good with all these claims in logs that anyone can see?

2021-11-15 07:15 UTC, merged

2021-11-15 12:43 UTC, BALAGA-GAYATRI commented
Printing token logs changes are removed from this PR and will be done post security approval.