Updated readme for allow-no-subscriptions input support
Azure/login pull request #79
Opened 2020-11-04 09:08 UTC by Ganeshrockz

2020-11-04 09:10 UTC, aksm-ms commented
@N-Usha please review.

2020-11-04 11:20 UTC, N-Usha requested changes

2020-11-04 11:20 UTC, N-Usha commented on README.md
>  NOTE: to manage service principals created with `az ad sp create-for-rbac`, visit the [Azure portal](https://portal.azure.com), navigate to your Azure Active Directory, then select **Manage** > **App
We should also add a mention about this new input in the introduction section : **GitHub Action for Azure Login**
With the Azure login Action, you can automate your workflow to do an Azure login using Azure service principal and run Azure CLI and Azure PowerShell scripts.

By default, the action only logs in with the Azure CLI (using the az login command). To log in with the Az PowerShell module, set enable-AzPSSession to true. To login to Azure tenants without any subscriptions,  set the optional parameter `allow-no-subscriptions` to `true`.

This repository contains GitHub Action for Azure Login.

2020-11-05 06:29 UTC, N-Usha approved these changes

2020-11-05 06:45 UTC, merged